clang:
  tags:
    - clang
  except:
    - macos
    - windows
  variables:
    CC: clang
    CXX: clang++
  before_script:
    - git submodule update --init --recursive
    - rm -rf build-*
  script:
    - mkdir build-clang
    - cd build-clang
    - cmake -DCMAKE_INSTALL_PREFIX:PATH=install ..
    - make clean
    - make
    - make install
    - export ARTIFACT_ID="${CI_PIPELINE_IID}-CI_JOB_NAME"
    - make deploy
    - ctest -VV

gcc:
  tags:
    - gcc
  except:
    - macos
    - windows
  variables:
    CC: gcc
    CXX: g++
  before_script:
    - git submodule update --init --recursive
    - rm -rf build-*
  script:
    - mkdir build-gcc
    - cd build-gcc
    - cmake -DCMAKE_INSTALL_PREFIX:PATH=install ..
    - make clean
    - make
    - make install
    - export ARTIFACT_ID="${CI_PIPELINE_IID}-CI_JOB_NAME"
    - make deploy
    - ctest -VV