stages:
  - test
  - build
  - deploy

workaround:
  stage: test
  tags:
    - aws
  allow_failure: true
  script:
    - ping -c 1 gitlab.com

clang:
  stage: build
  tags:
    - clang
  except:
    - macos
    - windows
  variables:
    CC: clang
    CXX: clang++
  before_script:
    - git submodule update --init --recursive
    - rm -rf build-*
  script:
    - mkdir build-clang
    - cd build-clang
    - cmake ..
    - make clean
    - make
    - make package
    - export ARTIFACT_ID="${CI_PIPELINE_IID}-${CI_JOB_NAME}"
    - make deploy
    - ctest -VV

gcc:
  stage: build
  tags:
    - gcc
  except:
    - macos
    - windows
  variables:
    CC: gcc
    CXX: g++
  before_script:
    - git submodule update --init --recursive
    - rm -rf build-*
  script:
    - mkdir build-gcc
    - cd build-gcc
    - cmake ..
    - make clean
    - make
    - make package
    - export ARTIFACT_ID="${CI_PIPELINE_IID}-${CI_JOB_NAME}"
    - make deploy
    - ctest -VV