clang:
  tags:
    - clang
  variables:
    CC: clang
    CXX: clang++
  before_script:
    - git submodule update --init --recursive
    - rm -rf build-*
  script:
    - mkdir build-clang
    - cd build-clang
    - cmake -DCMAKE_INSTALL_PREFIX:PATH=install ..
    - make
    - make install
    - make package
    - ctest -VV

gcc:
  tags:
    - gcc
  variables:
    CC: gcc
    CXX: g++
  before_script:
    - git submodule update --init --recursive
    - rm -rf build-*
  script:
    - mkdir build-gcc
    - cd build-gcc
    - cmake -DCMAKE_INSTALL_PREFIX:PATH=install ..
    - make
    - make install
    - make package
    - ctest -VV