language: cpp

os:
  - linux
  - osx
  - windows

dist:
  - xenial

compiler:
  - gcc
  - clang

before_script:
  - if [ "$TRAVIS_OS_NAME" == "windows" ] && [ "$CC" == "clang" ]; then
      export CC=clang-cl;
      export CXX=clang-cl;
      export CC_FOR_BUILD=clang-cl;
      export CXX_FOR_BUILD=clang-cl;
      clang-cl --version;
    fi
  - mkdir build
  - cd build
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      cmake .. -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND";
    else
      cmake ..;
    fi

script:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      mingw32-make VERBOSE=1 && mingw32-make test;
    else
      make && make test;
    fi
