language: cpp

os:
  - linux
  - osx

dist:
  - xenial

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      packages:
        - gcc-7
        - g++-7

before_script: 
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CC" == "gcc" ]; then
      export CC=gcc-7 ;
      export CXX=g++-7;
    fi
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test
