language: cpp

os:
  - osx

compiler:
  - gcc
  - clang

addons:
  homebrew:
    packages:
    - libtool
    - gcc

before_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$CC" == "gcc" ]; then
      export CC=$(ls /usr/local/Cellar/gcc/*/bin/gcc-?);
      export CXX=$(ls /usr/local/Cellar/gcc/*/bin/g++-?);
    fi
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ctest -VV