language: cpp

os:
  - osx

compiler:
  # - gcc
  - clang

addons:
  homebrew:
    packages:
    - libtool
    - gcc
    - python3

before_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$CC" == "gcc" ]; then
      export CC=$(ls /usr/local/Cellar/gcc/*/bin/gcc-?);
      export CXX=$(ls /usr/local/Cellar/gcc/*/bin/g++-?);
    fi
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=install ..

script:
  - make
  - make install
  - make package
  - ctest -VV