language: cpp

os:
  - linux
  - osx
  - windows

dist:
  - xenial

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      cmake .. -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND";
    else
      cmake ..;
    fi

script:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      mingw32-make;
      mingw32-make test;
    else
      make;
      make test;
    fi
