# Windows ci build script.
# Reference: https://github.com/travis-ci-tester/toolchain-table

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "MinGW Makefiles"

install:
  - cmd: git submodule update --init --recursive
  # Remove shell provided by git, to avoid conflicts.
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  # Python 3.
  - cmd: set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%
  # Tune locations.
  - cmd: set PATH=%cd%\_ci\cmake\bin;%PATH%
  - cmd: set MSYS_PATH=C:\msys64\usr\bin
  - cmd: set MINGW_ROOT=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64
  - cmd: set MINGW_PATH=%MINGW_ROOT%\bin
  # Required to build jemalloc.
  # - cmd: "%MSYS_PATH%\\pacman --noconfirm -Suy mingw-w64-x86_64-make"
  # - cmd: mkdir jemalloc\install
  # - cmd: type nul > jemalloc\install\libjemalloc.dll
  # Enable lto plugin for mingw.
  - cmd: mkdir %MINGW_ROOT%\lib\bfd-plugins
  - cmd: copy %MINGW_ROOT%\libexec\gcc\x86_64-w64-mingw32\8.1.0\liblto_plugin-0.dll %MINGW_ROOT%\lib\bfd-plugins\liblto_plugin-0.dll

build_script:
  - python .\jemalloc\build.py --prebuilt
  - python .\windows.py --generator "%GENERATOR%"

# Uncomment to be enable rdp.
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
