function(target_platform output_plt output_lib)
    if( WIN32 )
        message( STATUS "Compiling for windows." )
        set( ${output_plt} "win" PARENT_SCOPE )
        set( ${output_lib} "dll" PARENT_SCOPE )
        add_compile_definitions( "WIN32_LEAN_AND_MEAN" )
        add_compile_definitions( "UNICODE" )
        add_compile_definitions( "__USE_MINGW_ANSI_STDIO" )
        add_compile_definitions( "LINK_PE" )
    elseif( UNIX AND NOT APPLE )
        message( STATUS "Compiling for linux." )
        set( ${output_plt} "linux" PARENT_SCOPE )
        set( ${output_lib} "so" PARENT_SCOPE )
        add_compile_definitions( "_GNU_SOURCE" )
        add_compile_definitions( "LINK_ELF" )
    elseif( APPLE )
        message( STATUS "Compiling for macos." )
        set( ${output_plt} "mac" PARENT_SCOPE )
        set( ${output_lib} "dylib" PARENT_SCOPE )
        add_compile_definitions( "LINK_MACHO" )
    else()
        message( FATAL_ERROR "Unsupported OS!!!" )
    endif()
endfunction()